In [4]:
import pandas as pd
import nltk
from collections import defaultdict
from datetime import timedelta
import matplotlib.pyplot as plt
import numpy as np
import os
import re
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

# Create a directory for saving charts
os.makedirs('charts', exist_ok=True)

In [5]:
# Import styling module - now available in the main directory
from style_dataframes import enable_styled_print

# Enable styled printing - this will make all print(df) statements show Excel-like tables
enable_styled_print()

Excel-like styling enabled for DataFrames with print()!
Your existing print(df) statements will now show styled tables.
To disable, call disable_styled_print()

In [6]:
df = pd.read_csv('whatsapp_final_processed_v4.csv')
print(df.head())